### ISSUE TITLE
"these parameters are deprecated, see docs for addKeyword" Error with AJV v8+

### ISSUE THREAD

**Issue by pkyeck** [jdthorpe/ajv-semver#15]
I get this error trying to add semver-support like this:

```typescript
import Ajv from 'ajv';
import initAjvFormats from 'ajv-formats';
import initAjvSemver from 'ajv-semver';

export const customAjv = new Ajv({
  coerceTypes: true,
  useDefaults: true,
  removeAdditional: true,
  allErrors: false,
});

initAjvFormats(customAjv);
initAjvSemver(customAjv);
```

```
these parameters are deprecated, see docs for addKeyword
```

`package.json`

```
"dependencies": {
    "ajv": "^8.12.0",
    "ajv-formats": "^2.1.1",
    "ajv-semver": "^1.0.5"
},
```

I tried looking at the AJV ref for `addKeyword` but after briefly scanning it, I didn't find any info about a deprecation...

- https://ajv.js.org/api.html#ajv-addkeyword-definition-string-object-ajv
- https://ajv.js.org/keywords.html#define-keyword-with-compile-function

maybe you see what has to be changes/updated for this warning to go away.

Thanks

**Comment by jdthorpe** [comment]
I pushed a fix to github just now, with all tests passing with AJV 8.12.0.  I'll push to npm soon.

**Comment by jdthorpe** [comment]
Bumped version to 2.0.0
