### ISSUE TITLE
v2.0.0 has no index.d.ts included 

### ISSUE THREAD

**Issue by pkyeck** [jdthorpe/ajv-semver#17]
Linter is complaining: 

```
Could not find a declaration file for module 'ajv-semver'. '/abc/node_modules/ajv-semver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ajv-semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'ajv-semver';`ts(7016)
```

I looked into both packages
- ajv-semver-1.0.5.tgz
- ajv-semver-2.0.0.tgz

and the v2.0.0 is missing the `index.d.ts`.

Could you please re-publish a v2.0.1 with the types included? Thanks!

**Comment by jdthorpe** [comment]
Added the types (`index.d.ts`) and bumped to 2.0.1.

**Comment by pkyeck** [comment]
Thanks a lot - that was fast 👌
