### ISSUE TITLE
Coercion

### ISSUE THREAD

**Issue by carlo-quinonez** [jdthorpe/ajv-semver#18]
We're collecting IoT data from devices built by various divisions in the company. The biggest challenge is low quality data - different divisions pay more or less attention to the data they're sending up. We've made the data pipeline as forgiving of bad dat as possible. For example, even though we 'require' teams to send datetimes as ISO8601 strings, the datapipeline actually accepts linux epoch times (either seconds or milliiseconds) as well as the standard unix format (`Tue Jun  6 16:24:40 PDT 2023`) by  coercing them into ISO8601 strings.

Can this module support for coercion of versions, like ` v1` , `1.0`, `v1.0`, etc, into valid semver? The `semver` module provides a [`coerce` function ](https://github.com/npm/node-semver/blob/main/functions/coerce.js) that does this, so the heavy lifting is already done.

Coercion should probably be a configurable option since it looks like an expensive operation.

I could work on a PR if it's appropriate.

**Comment by jdthorpe** [comment]
This could probably be done without that much effort.  There are already functions that modify a semver string [here](https://github.com/jdthorpe/ajv-semver/blob/e210606e3618dbaa53d5a12c18174bd2391db563/index.ts#L92).  You could probably use that bit of code as a template to introduce a "coerce" option.

I'd fully support a PR, but won't have time to do it my self in the near future.  This repo has some pretty thorough testing that you can run in the usual way (`npm run test`). If you add coercion functionality and tests to go along with it (and the other tests pass too),  I'd happily accept a PR

**Comment by carlo-quinonez** [comment]
I realized this is already possible using the `clean` and `loose` options.

```js
var Ajv = require("ajv");
var ajv = new Ajv();
require("ajv-semver")(ajv);

const validator = ajv.compile({
  type: "object",
  properties: {
    version: {
      type: "string",
      semver: {
        clean: true,
        loose: true
      },
    },
  },
});

let dirty = { version: "v1.2.3asdfasdf" }; 

console.log(validator(dirty))      // true
console.dir(dirty)                 // '1.2.3-asdfasdf' coerced to a clean semver
```

**Comment by jdthorpe** [comment]
Sweet!  Glad it worked out for you :)
