### ISSUE TITLE
Global regex modifier causing unexpected behavior

### ISSUE THREAD

**Issue by eric-gonzalez-tfs** [jdthorpe/ajv-semver#19]
I noticed some strange behavior when trying to validate `semver` formatted strings. Completely valid versions weren't always being marked as valid - see below.

![Screenshot 2023-12-07 at 2 15 54 PM](https://github.com/jdthorpe/ajv-semver/assets/82120345/52fa443f-9607-48f7-9e31-e7144b0fb810)

Ultimately what it came down to was the `/g` flag on [the regex](https://github.com/jdthorpe/ajv-semver/blob/e210606e3618dbaa53d5a12c18174bd2391db563/index.ts#L10) was causing issues because the regex requires a reset.

## Suggestions
- Remove the global flag altogether if it is not needed.
- Convert the format into a function that resets the `lastIndex` on the regex whenever the regex is used. See `ajv-formats` as an [example](https://github.com/ajv-validator/ajv-formats/blob/master/src/formats.ts#L237-L242).

**Comment by jdthorpe** [comment]
Thanks for this issue and recommended fix. I should be able to up date this in the next couple days.

**Comment by jdthorpe** [comment]
Removed the global flag per [this recommendation](https://github.com/ajv-validator/ajv/issues/2291#issuecomment-1656660438)
